// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPendingJob = `-- name: CancelPendingJob :one
UPDATE jobs
SET
    status = 'cancelled',
    updated_at = NOW()
WHERE id = $1
    AND status = 'pending'
RETURNING id, type, payload, status, attempt, max_attempts, run_at, locked_at, locked_by, last_error, idempotency_key, created_at, updated_at
`

func (q *Queries) CancelPendingJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, cancelPendingJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RunAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimJobs = `-- name: ClaimJobs :many
WITH selected_jobs AS (
    SELECT id
    FROM jobs
    WHERE status = 'pending'
        AND run_at <= NOW()
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
UPDATE jobs
SET
    status = 'processing',
    locked_at = NOW(),
    locked_by = $2,
    updated_at = NOW()
FROM selected_jobs
WHERE jobs.id = selected_jobs.id
RETURNING jobs.id, jobs.type, jobs.payload, jobs.status, jobs.attempt, jobs.max_attempts, jobs.run_at, jobs.locked_at, jobs.locked_by, jobs.last_error, jobs.idempotency_key, jobs.created_at, jobs.updated_at
`

type ClaimJobsParams struct {
	Limit    int32       `json:"limit"`
	LockedBy pgtype.Text `json:"locked_by"`
}

func (q *Queries) ClaimJobs(ctx context.Context, arg ClaimJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, claimJobs, arg.Limit, arg.LockedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RunAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.LastError,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    id,
    type,
    payload,
    status,
    max_attempts,
    run_at,
    idempotency_key
)
VALUES (
    $1,
    $2,
    $3,
    'pending',
    $4,
    $5,
    $6
)
RETURNING id, type, payload, status, attempt, max_attempts, run_at, locked_at, locked_by, last_error, idempotency_key, created_at, updated_at
`

type CreateJobParams struct {
	ID             pgtype.UUID        `json:"id"`
	Type           string             `json:"type"`
	Payload        []byte             `json:"payload"`
	MaxAttempts    int32              `json:"max_attempts"`
	RunAt          pgtype.Timestamptz `json:"run_at"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.Type,
		arg.Payload,
		arg.MaxAttempts,
		arg.RunAt,
		arg.IdempotencyKey,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RunAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, type, payload, status, attempt, max_attempts, run_at, locked_at, locked_by, last_error, idempotency_key, created_at, updated_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RunAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByIdempotencyKey = `-- name: GetJobByIdempotencyKey :one
SELECT id, type, payload, status, attempt, max_attempts, run_at, locked_at, locked_by, last_error, idempotency_key, created_at, updated_at
FROM jobs
WHERE idempotency_key = $1
`

func (q *Queries) GetJobByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIdempotencyKey, idempotencyKey)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RunAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
