// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID             pgtype.UUID        `json:"id"`
	Type           string             `json:"type"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempt        int32              `json:"attempt"`
	MaxAttempts    int32              `json:"max_attempts"`
	RunAt          pgtype.Timestamptz `json:"run_at"`
	LockedAt       pgtype.Timestamptz `json:"locked_at"`
	LockedBy       pgtype.Text        `json:"locked_by"`
	LastError      pgtype.Text        `json:"last_error"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
